#ifndef VIEWS_STANDARD_DEFINITIONS_ERROR_H_INCLUDED
#define VIEWS_STANDARD_DEFINITIONS_ERROR_H_INCLUDED

#include "Views.h"

#define ERR_PREFIX VIW
#define ERR_MAXLENGTH 10000

#ifndef VIW_MAXARCHIVED
#define VIW_MAXARCHIVED 10
#endif

#define ERR_MAXARCHIVED VIW_MAXARCHIVED

#include "Error.h"


// Error type
enum VIW_ID_ErrorType
{
    VIW_ID_ERRORTYPE_NONE = 0,
    VIW_ID_ERRORTYPE_WARNING = 1,
    VIW_ID_ERRORTYPE_ERROR = 2,
    VIW_ID_ERRORTYPE_FATAL = 3
};

// Error id
enum _VIW_ID_ErrorID
{
    _VIW_ID_ERRORID_GENERAL_NONE = 0x00000000,
    _VIW_ID_ERRORID_UPDATESHAPEADVANCED_X = 0x00010200,
    _VIW_ID_ERRORID_UPDATESHAPEADVANCED_Y = 0x00010201,
    _VIW_ID_ERRORID_UPDATESHAPEADVANCED_DATA = 0x00010202,
    _VIW_ID_ERRORID_UPDATESHAPECOORD_TYPE = 0x00020200,
    _VIW_ID_ERRORID_UPDATESHAPECOORD_STRETCH = 0x00020201,
    _VIW_ID_ERRORID_UPDATESHAPECOORD_ORIGIN = 0x00020202,
    _VIW_ID_ERRORID_GETANCHORPOINT_ANCHORTYPE = 0x00030200,
    _VIW_ID_ERRORID_GETANCHORPOINT_REF = 0x00030201,
    _VIW_ID_ERRORID_GETBIASANCHORPOINT_ANCHOR = 0x00040200,
    _VIW_ID_ERRORID_GETPOS_TYPE = 0x00050200,
    _VIW_ID_ERRORID_GETPOS_POINTER = 0x00050201,
    _VIW_ID_ERRORID_GETPOS_POINTERABS = 0x00050202,
    _VIW_ID_ERRORID_GETPOS_SINGLEANCHOR = 0x00050203,
    _VIW_ID_ERRORID_GETPOS_BIASANCHOR = 0x00050204,
    _VIW_ID_ERRORID_GETPOS_NONE = 0x00050205,
    _VIW_ID_ERRORID_GETSIZEDIFF_POS = 0x00060200,
    _VIW_ID_ERRORID_FINDREFVIEW_TYPE = 0x00070200,
    _VIW_ID_ERRORID_FINDREFVIEW_FIRSTCHILD = 0x00070201,
    _VIW_ID_ERRORID_FINDREFVIEW_NONE = 0x00070202,
    _VIW_ID_ERRORID_GETSIZECOPY_REF = 0x00080200,
    _VIW_ID_ERRORID_GETSIZECOPY_TYPE = 0x00080201,
    _VIW_ID_ERRORID_GETSIZE_TYPE = 0x00090200,
    _VIW_ID_ERRORID_GETSIZE_POINTER = 0x00090201,
    _VIW_ID_ERRORID_GETSIZE_DIFF = 0x00090202,
    _VIW_ID_ERRORID_GETSIZE_COPY = 0x00090203,
    _VIW_ID_ERRORID_UPDATESHAPECOORDORIGIN_POS = 0x000A0200,
    _VIW_ID_ERRORID_UPDATESHAPECOORDORIGIN_TYPE = 0x000A0201,
    _VIW_ID_ERRORID_UPDATESHAPECOORDORIGIN_SIZE = 0x000A0202,
    _VIW_ID_ERRORID_UPDATESHAPECOORDSTRETCH_POS = 0x000B0200,
    _VIW_ID_ERRORID_ADDTOVIEWLIST_LIST = 0x000C0200,
    _VIW_ID_ERRORID_REMOVEFROMVIEWLIST_WARNING = 0x000D0100,
    _VIW_ID_ERRORID_REMOVEFROMVIEWLIST_ERROR = 0x000D0201,
    _VIW_ID_ERRORID_CREATEROOT_MALLOC = 0x000E0200,
    _VIW_ID_ERRORID_CREATEROOT_LIST = 0x000E0201,
    _VIW_ID_ERRORID_CREATEROOT_PROPERTY = 0x000E0202,
    _VIW_ID_ERRORID_CREATEROOT_WINDOWID = 0x000E0203,
    _VIW_ID_ERRORID_UPDATESHAPE_CHILD = 0x000F0200,
    _VIW_ID_ERRORID_UPDATESHAPE_TYPE = 0x000F0201,
    _VIW_ID_ERRORID_UPDATESHAPE_PROPERTY = 0x000F0202,
    _VIW_ID_ERRORID_UPDATESHAPE_SIBLING = 0x000F0203,
    _VIW_ID_ERRORID_UPDATESHAPE_NEXTSIBLING = 0x000F0204,
    _VIW_ID_ERRORID_UPDATESHAPE_WINDOW = 0x000F0205,
    _VIW_ID_ERRORID_UPDATESHAPE_COPY = 0x000F0206,
    _VIW_ID_ERRORID_UPDATESHAPE_ADVANCED = 0x000F0207,
    _VIW_ID_ERRORID_UPDATESHAPE_TYPENONE = 0x000F0108,
    _VIW_ID_ERRORID_CREATEPROPERTYBASE_MALLOC = 0x00100200,
    _VIW_ID_ERRORID_CREATEPROPERTYBASE_MALLOCSCRIPT = 0x00100201,
    _VIW_ID_ERRORID_CREATEPROPERTYBASE_NEXTBASE = 0x00100202,
    _VIW_ID_ERRORID_CREATEPROPERTYBASE_LINKSCRIPT = 0x00100203,
    _VIW_ID_ERRORID_CREATEVIEW_MALLOC = 0x00110200,
    _VIW_ID_ERRORID_CREATEVIEW_CHILDLIST = 0x00110201,
    _VIW_ID_ERRORID_CREATEPROPERTYSCRIPT_MALLOC = 0x00120200,
    _VIW_ID_ERRORID_CREATEPROPERTYSCRIPT_NEXTBASE = 0x00120201,
    _VIW_ID_ERRORID_CREATEPROPERTYSCRIPT_ADDTOLIST = 0x00120202,
    _VIW_ID_ERRORID_CREATESCRIPTVIEW_NEXTBASE = 0x00130200,
    _VIW_ID_ERRORID_CREATESCRIPTVIEW_CREATEVIEW = 0x00130201,
    _VIW_ID_ERRORID_CREATESCRIPTVIEW_PROPERTY = 0x00130202,
    _VIW_ID_ERRORID_CREATESCRIPTVIEW_TIME = 0x00130204,
    _VIW_ID_ERRORID_CREATESCRIPTVIEW_ORDER = 0x00130206,
    _VIW_ID_ERRORID_ADDREF_REFNOTFOUND = 0x00140100,
    _VIW_ID_ERRORID_ADDREF_TYPE = 0x00140201,
    _VIW_ID_ERRORID_ADDREF_FIRSTCHILD = 0x00140202,
    _VIW_ID_ERRORID_USEADVANCEDSHAPEDATA_MALLOC = 0x00150200,
    _VIW_ID_ERRORID_USEADVANCEDSHAPEDATA_INIT = 0x00150101,
    _VIW_ID_ERRORID_UPDATESHAPECOPY_REF = 0x00160200,
    _VIW_ID_ERRORID_RUNSCRIPT_FUNCTION = 0x00170100,
    _VIW_ID_ERRORID_RUNSCRIPT_RUNWARNING = 0x00170101,
    _VIW_ID_ERRORID_RUNSCRIPT_RUNERROR = 0x00170202,
    _VIW_ID_ERRORID_RUNSCRIPT_TYPE = 0x00170203,
    _VIW_ID_ERRORID_ADDTOLIST_POS = 0x00180200,
    _VIW_ID_ERRORID_ADDTOLIST_REALLOC = 0x00180201,
    _VIW_ID_ERRORID_REMOVEFROMLIST_LOCATE = 0x00190100,
    _VIW_ID_ERRORID_REMOVEFROMLIST_REALLOC = 0x00190201,
    _VIW_ID_ERRORID_ADDTOSCRIPTLIST_LISTWARNING = 0x001A0100,
    _VIW_ID_ERRORID_ADDTOSCRIPTLIST_LISTERROR = 0x001A0201,
    _VIW_ID_ERRORID_ADDTOSCRIPTLIST_SORT = 0x001A0302,
    _VIW_ID_ERRORID_REMOVEFROMSCRIPTLIST_WARNING = 0x001B0100,
    _VIW_ID_ERRORID_REMOVEFROMSCRIPTLIST_ERROR = 0x001B0201,
    _VIW_ID_ERRORID_UPDATESCRIPTLIST_LOCATE = 0x001C0100,
    _VIW_ID_ERRORID_UPDATESCRIPTORDER_UPDATELIST = 0x001D0200,
    _VIW_ID_ERRORID_FINDBASE_NOBASE = 0x001E0200,
    _VIW_ID_ERRORID_UPDATESCRIPTTIME_OWNSCRIPT = 0x001F0200,
    _VIW_ID_ERRORID_FINDNEXTBASE_ROOT = 0x00200200,
    _VIW_ID_ERRORID_FINDNEXTBASE_NOBASE = 0x00200201,
    _VIW_ID_ERRORID_CREATEBASEVIEW_VIEW = 0x00210200,
    _VIW_ID_ERRORID_CREATEBASEVIEW_PROPERTY = 0x00210201,
    _VIW_ID_ERRORID_CREATEBASEVIEW_ORDERSCRIPT = 0x00210202,
    _VIW_ID_ERRORID_CREATESUBVIEW_NEXTBASE = 0x00220200,
    _VIW_ID_ERRORID_CREATESUBVIEW_VIEW = 0x00220201,
    _VIW_ID_ERRORID_CREATESUBVIEW_BASE = 0x00220202
};

// Error messages
// Type errors
#define _VIW_STRING_ERROR_TYPENONE "The type was \"None\""
#define _VIW_STRING_ERROR_UNKNOWNTYPE "Unknown type (%u)"
#define _VIW_STRING_ERROR_NOBASE "Neither the selected view or it's child has a \"Base\" property"

// Update errors
#define _VIW_STRING_ERROR_UPDATESHAPEWINDOW "Unable to update shape using window size"
#define _VIW_STRING_ERROR_UPDATESHAPECOPY "Unable to update shape by copying another shape"
#define _VIW_STRING_ERROR_UPDATESHAPEADVANCED "Unable to update shape using shape data"
#define _VIW_STRING_ERROR_UPDATEPROPERTY "Unable to update property"
#define _VIW_STRING_ERROR_UPDATECHILD "Unable to update child"
#define _VIW_STRING_ERROR_UPDATESIBLING "Unable to update siblings"
#define _VIW_STRING_ERROR_UPDATENEXTSIBLING "Unable to update next sibling"
#define _VIW_STRING_ERROR_UPDATEX "Unable not update x"
#define _VIW_STRING_ERROR_UPDATEY "Unable not update y"
#define _VIW_STRING_ERROR_SETSHAPESTRETCH "Unable to set shape using \"Stretch\" method"
#define _VIW_STRING_ERROR_SETSHAPEORIGIN "Unable to set shape using \"Origin\" method"
#define _VIW_STRING_ERROR_UPDATESCRIPTORDER "Unable to update script order"
#define _VIW_STRING_ERROR_UPDATETIME "Unable to update time"

// Window errors
#define _VIW_ID_STRING_WINDOWID "Unable to get the window ID"

// Pointer/reference errors
#define _VIW_STRING_ERROR_NOREF "Unable to find reference view"
#define _VIW_STRING_ERROR_SHAPEDATA "No shape data is available"
#define _VIW_STRING_ERROR_NOPOINTER "No pointer has not been specified"

// Calculation error
#define _VIW_STRING_ERROR_CALCPOS "Unable to calculate the position"
#define _VIW_STRING_ERROR_CALCSIZE "Unable to calculate the size"
#define _VIW_STRING_ERROR_ANCHORERROR "The anchor point could not be found"

// Invalid errors
#define _VIW_STRING_ERROR_FIRSTCHILD "Reference to earlier sibling is invalid because this is the first child"
#define _VIW_STRING_ERROR_DATAINITIALIZED "Data is already initialized"

// Create error
#define _VIW_STRING_ERROR_MALLOC "Unable to allocate memory"
#define _VIW_STRING_ERROR_REALLOC "Unable to reallocate memory"
#define _VIW_STRING_ERROR_CREATEVIEW "Unable to create view"
#define _VIW_STRING_ERROR_CREATEBASE "Unable to create \"Base\" view"

// Perform error
#define _VIW_STRING_ERROR_ADDPROPERTY "Unable to add property"
#define _VIW_STRING_ERROR_ADDBASEPROPERTY "Unable to add \"Base\" property"
#define _VIW_STRING_ERROR_ADDSCRIPTPROPERTY "Unable to add \"Script\" property"
#define _VIW_STRING_ERROR_ADDROOTLIST "Unable to add root to list of roots"
#define _VIW_STRING_ERROR_ADDCHILDLIST "Unable to add view to child list"

#define _VIW_STRING_ERROR_LOCATEOBJECT "Unable to locate object"
#define _VIW_STRING_ERROR_UPDATESHAPE "Unable to update shape"
#define _VIW_STRING_ERROR_REMOVEROOTLIST "Unable to remove root from list of roots"
#define _VIW_STRING_ERROR_RANGE "The specified value is outside its allowed range"
#define _VIW_STRING_ERROR_DESTROYCHILD "Unable to destroy child"
#define _VIW_STRING_ERROR_REMOVECHILDLIST "Unable to remove from child list"
#define _VIW_STRING_ERROR_DESTROYVIEW "Unable to destroy view"
#define _VIW_STRING_ERROR_ILLIGALREF "This reference is not legal"
#define _VIW_STRING_ERROR_NULLFUNCTION "The function is NULL and cannot be used"
#define _VIW_STRING_ERROR_SCRIPT "Error when running script"
#define _VIW_STRING_ERROR_NEXTBASE "There were no direct ancestor with a \"base\" property"
#define _VIW_STRING_ERROR_ADDTOLIST "Unable to add object to list"
#define _VIW_STRING_ERROR_REMOVEFROMLIST "Unable to remove object from list"
#define _VIW_STRING_ERROR_SORTLIST "Unable to sort list"
#define _VIW_STRING_ERROR_NOSCRIPT "No script is defined"
#define _VIW_STRING_ERROR_ROOTNEXTBASE "A root has no next base"
#define _VIW_STRING_ERROR_ADDTOSCRIPTLIST "Unable to add script to script list"

#endif