#ifndef VIEWS_GRAPHICS_DEFINITIONS_ERROR
#define VIEWS_GRAPHICS_DEFINITIONS_ERROR

enum _VIW_Graphics_ID_ErrorID
{
    _VIW_ID_ERRORID_CREATECANVAS_CANVAS = 0x201010200,
    _VIW_ID_ERRORID_DESTROYCANVAS_INIT = 0x201020100,
    _VIW_ID_ERRORID_CREATEPROPERTYGRAPHICS_MALLOC = 0x201030200,
    _VIW_ID_ERRORID_CREATEPROPERTYGRAPHICS_BASLIST = 0x201030201,
    _VIW_ID_ERRORID_DESTROYPROPERTYGRAPHICS_LIST = 0x201040300,
    _VIW_ID_ERRORID_RUNPROPERTYGRAPHICS_COPY = 0x201050200,
    _VIW_ID_ERRORID_RUNPROPERTYGRAPHICS_RUNEXIST = 0x201050101,
    _VIW_ID_ERRORID_RUNPROPERTYGRAPHICS_RUN = 0x201050202
};

// Error strings
// Type errors
#define _VIW_STRING_ERROR_TYPE "Wrong type (%u)"

// Initialisation errors
#define _VIW_STRING_ERROR_ALREADYINIT "Struct has already been initialised"
#define _VIW_STRING_ERROR_NOTINIT "Struct has not been initialised"
#define _VIW_STRING_ERROR_TEXTURE "Unable to create texture"

// Render errors
#define _VIW_STRING_ERROR_COPYTEXTURE "Unable to copy texture onto renderer"
#define _VIW_STRING_ERROR_RENDER "Unable to render view"

#endif // VIEWS_GRAPHICS_DEFINITIONS_ERROR