#ifndef VIEWS_STANDARD_DEFINITIONS_ID_H_INCLUDED
#define VIEWS_STANDARD_DEFINITIONS_ID_H_INCLUDED

// Anchor id
enum VIW_ID_Anchor
{
    VIW_ID_ANCHOR_CENTER,
    VIW_ID_ANCHOR_POS,
    VIW_ID_ANCHOR_NEG
};

// Relation id
enum VIW_ID_Relation
{
    VIW_ID_RELATION_NONE,
    VIW_ID_RELATION_ROOT,
    VIW_ID_RELATION_PARENT,
    VIW_ID_RELATION_SIBLING,
    VIW_ID_RELATION_ID
};

// Position type id
enum VIW_ID_Pos
{
    VIW_ID_POS_NONE,
    VIW_ID_POS_RIGID,
    VIW_ID_POS_RIGID_ABS,
    VIW_ID_POS_POINTER,
    VIW_ID_POS_POINTER_ABS,
    VIW_ID_POS_SINGLE,
    VIW_ID_POS_BIAS
};

// Size copy type id
enum VIW_ID_SizeCopy
{
    VIW_ID_SIZECOPY_WIDTH,
    VIW_ID_SIZECOPY_HEIGHT
};

// Size type id
enum VIW_ID_Size
{
    VIW_ID_SIZE_NONE,
    VIW_ID_SIZE_RIGID,
    VIW_ID_SIZE_POINTER,
    VIW_ID_SIZE_DIFF,
    VIW_ID_SIZE_COPY
};

// Rect type id
enum VIW_ID_Rect
{
    VIW_ID_RECT_NONE,
    VIW_ID_RECT_STRETCH,
    VIW_ID_RECT_ORIGIN
};

// Shape type id
enum VIW_ID_Shape
{
    VIW_ID_SHAPE_NONE,
    VIW_ID_SHAPE_COPY,
    VIW_ID_SHAPE_ADVANCED,
    VIW_ID_SHAPE_WINDOW
};

// Property id
enum VIW_ID_Property
{
    VIW_ID_PROPERTY_NONE,
    VIW_ID_PROPERTY_BASE,
    VIW_ID_PROPERTY_SCRIPT,
    VIW_ID_PROPERTY_EVENT,
    VIW_ID_PROPERTY_GRAPHICSFILL,
    VIW_ID_PROPERTY_GRAPHICSIMAGE,
    VIW_ID_PROPERTY_GRAPHICSTEXT
};

// Return values for error
#define VIW_ID_RETURNERROR_POINTER (NULL)
#define VIW_ID_RETURNERROR_INT32_T (-2147483648)

#endif