#ifndef VIEWS_GRAPHICS_DEFINITIONS_ERROR
#define VIEWS_GRAPHICS_DEFINITIONS_ERROR

enum _VIW_Graphics_ID_ErrorID
{
    _VIW_ID_ERRORID_GENERAL_NONE = 0x200000000
};


#endif // VIEWS_GRAPHICS_DEFINITIONS_ERROR